routes/admin.php
<?php

Route::get('/home', function () {
    $users[] = Auth::user();
    $users[] = Auth::guard()->user();
    $users[] = Auth::guard('admin')->user();

    //dd($users);

    return view('admin.home');
})->name('home');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//RUTAS DE LIstas COMPARTIDOS
Route::group(['middleware'=>'shared'],function (){
	Route::get('shared/shoppinglist/{shareable_link}','ShoppinglistController@shared_link');
});

//RUTAS DE USUARIO
Route::group(['middleware'=>'auth'],function (){
	Route::resource('shoppinglist','ShoppinglistController');
	Route::get('edit/{id}/shopping','ShoppinglistController@shopping')->name('shoppinglist.shopping');
	Route::put('/shopping/{id}','ShoppinglistController@update_shopping')->name('shoppinglist.update');
});

//RUTAS DE ADMINISTRADOR
Route::group(['prefix' => 'admin'], function () {
    Route::group(['middleware'=>'auth:admin'],function (){
        Route::get('/register', 'AdminAuth\RegisterController@showRegistrationForm')->name('admin.register');
        Route::post('/register', 'AdminAuth\RegisterController@register');
        Route::resource('category','CategoryController');
		Route::get('product/deleted','ProductController@deleted')->name('product.deleted');
		Route::patch('product/deleted/{id}','ProductController@restore_deleted')->name('product.restore');
		Route::delete('product/deleted/{id}','ProductController@delete_permanent')->name('product.perma_delete');
		Route::resource('product','ProductController');
	});

    //RUTAS DE LOGIN ADMIN
  Route::get('/login', 'AdminAuth\LoginController@showLoginForm')->name('admin.login');
  Route::post('/login', 'AdminAuth\LoginController@login');
  Route::post('/logout', 'AdminAuth\LoginController@logout')->name('admin.logout');


//RUTAS DE CONTRASEÑA ADMIN
  Route::post('/password/email', 'AdminAuth\ForgotPasswordController@sendResetLinkEmail')->name('admin.password.request');
  Route::post('/password/reset', 'AdminAuth\ResetPasswordController@reset')->name('admin.password.email');
  Route::get('/password/reset', 'AdminAuth\ForgotPasswordController@showLinkRequestForm')->name('admin.password.reset');
  Route::get('/password/reset/{token}', 'AdminAuth\ResetPasswordController@showResetForm');
});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/home.css') }}" rel="stylesheet">
</head>
<body>
<div id="app">
    {{--<nav class="navbar navbar-expand-lg navbar-light bg-light">--}}
        {{--<div class="container">--}}
            {{--<a class="navbar-brand" href="{{ url('/') }}">--}}
                {{--{{ config('app.name', 'Laravel') }}--}}
            {{--</a>--}}
            {{--<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"--}}
                    {{--aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">--}}
                {{--<span class="navbar-toggler-icon"></span>--}}
            {{--</button>--}}

            {{--<div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">--}}
                {{--<ul class="navbar-nav">--}}
                    {{--@if (Auth::guest())--}}
                        {{--<li class="nav-item"><a href="{{ route('login') }}" class="nav-link">Login</a></li>--}}
                    {{--@else--}}
                        {{--<li class="nav-item"><a href="{{ route('shoppinglist.index') }}" class="nav-link">Mis listas</a></li>--}}
                        {{--<li class="nav-item dropdown">--}}
                            {{--<a href="#" class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown"--}}
                               {{--aria-haspopup="true" aria-expanded="false">--}}
                                {{--{{ Auth::user()->name }}--}}
                            {{--</a>--}}
                            {{--<div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">--}}
                                {{--<a href="{{ route('logout') }}" class="dropdown-item"--}}
                                   {{--onclick="event.preventDefault();document.getElementById('logout-form').submit();">--}}
                                    {{--Logout--}}
                                {{--</a>--}}

                                {{--<form id="logout-form" action="{{ route('logout') }}" method="POST"--}}
                                      {{--style="display: none;">--}}
                                    {{--{{ csrf_field() }}--}}
                                {{--</form>--}}
                            {{--</div>--}}
                        {{--</li>--}}
                    {{--@endif--}}
                {{--</ul>--}}
            {{--</div>--}}

        {{--</div>--}}
    {{--</nav>--}}
    <header>
        @include('partials.home.nav')
    </header>
    <section class="d-flex justify-content-between">
        <div>

        </div>
        <div>
            <button><i class="fa fa-power-off"></i></button>
        </div>
    </section>
    @yield('content')
</div>

<!-- Scripts -->
<script src="{{ asset('js/app.js') }}"></script>
@yield('script')
</body>
</html>

resources/views/layouts/home.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Shop List - La Colonia</title>

    <!-- Fonts -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/home.css') }}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Raleway:100,600" rel="stylesheet" type="text/css">
</head>
<body>
<div id="app">
    <header>
            @include('partials.home.nav')
    </header>
    @yield('content')
</div>
<script src="{{ asset('js/app.js') }}"></script>
</body>
</html>